# SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
# SPDX-License-Identifier: MIT

[files]
extend-exclude = [
    "eo-runtime/src/main/java/EOorg/EOeolang/EOfs/EOfile$EOis_directory.java",
    "eo-parser/src/test/resources/org/eolang/parser/benchmark/native.xmir"
]

[default]
extend-ignore-identifiers-re = [
  "Olt*",       # false positive
  "Onot",       # false positive
  "BA",         # false positive
  "thi",        # false positive
  "lowcase",    # false positive
  "[D,d]atas*", # valid variable names
  "thr",        # valid variable name
  "cutted",     # valid variable name
  "splitted",   # valid variable name
  "scrpt",      # valid variable name
  "fle"         # valid variable name
]
