# SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
# SPDX-License-Identifier: MIT

version = 1
[[annotations]]
path = [
    ".codenarc",
    ".DS_Store",
    ".gitattributes",
    ".gitignore",
    ".mvn/jvm.config",
    ".pdd",
    ".xcop",
    "**.csv",
    "**.json",
    "**.md",
    "**.txt",
    "**.vm",
    "**/.DS_Store",
    "**/.gitignore",
    "**/.pdd",
    "**/.xcop",
    "**/*.csv",
    "**/*.jpg",
    "**/*.json",
    "**/*.md",
    "**/*.pdf",
    "**/*.phi",
    "**/*.png",
    "**/*.svg",
    "**/*.txt",
    "**/*.vm",
    "**/CITATION.cff",
    "**/CNAME",
    "**/javax.xml.transform.TransformerFactory",
    "**/javax.xml.xpath.XPathFactory",
    "**/MANIFEST.MF",
    "**/README.md",
    "CITATION.cff",
    "CNAME",
    "CODE_OF_CONDUCT.md",
    "eo-maven-plugin/src/main/resources/org/eolang/maven/latex/latex-template.txt",
    "eo-maven-plugin/src/test/resources/org/eolang/maven/commits/tags.txt",
    "eo-runtime/src/main/resources/org/eolang/version.txt",
    "MANIFEST.MF",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2016-2026 Objectionary.com"
SPDX-License-Identifier = "MIT"
