# SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: codenarc
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  codenarc:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
      - run: |
          wget --quiet https://repo1.maven.org/maven2/org/codenarc/CodeNarc/3.5.0/CodeNarc-3.5.0-all.jar
          java -cp CodeNarc-3.5.0-all.jar \
            org.codenarc.CodeNarc \
            -report=text:stdout \
            -maxPriority1Violations=0 \
            -maxPriority2Violations=0 \
            -maxPriority3Violations=0 \
            -failOnError=true \
            -rulesetfiles=file:.codenarc
