# The MIT License (MIT)
#
# SPDX-FileCopyrightText: Copyright (c) 2016-2025 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: infer
'on':
  push:
    branches:
      - master
jobs:
  infer:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: srz-zumix/setup-infer@v1
        with:
          infer_version: v1.0.0
      - run: infer --version
      - run: infer run --fail-on-issue --no-progress-bar -- mvn test
