# SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: loc-badge
'on':
  push:
    branches:
      - master
concurrency:
  group: loc-badge-${{ github.ref }}
  cancel-in-progress: true
jobs:
  loc-badge:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: shadowmoose/GHA-LoC-Badge@1.0.0
        with:
          debug: true
          directory: .
          badge: gh-pages/loc-badge.svg
      - if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: peter-evans/create-pull-request@v8
        with:
          sign-commits: true
          branch: loc-badge
          commit-message: 'new LoC badge'
          delete-branch: true
          title: 'Update LoC badge'
          assignees: yegor256
          base: gh-pages
