# SPDX-FileCopyrightText: Copyright (c) 2016-2025 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: Post Benchmark Comment
on:
  workflow_run:
    workflows: [ "Performance Regression Check" ]
    types:
      - completed

jobs:
  post-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Show PR Number
        run: echo "The PR number is ${{ github.event.workflow_run.pull_requests[0].number }}"
      - name: Download Benchmark Comment
        uses: actions/download-artifact@v4
        with:
          name: benchmark-comment
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Post Comment on PR
        uses: mshick/add-pr-comment@v2
        with:
          issue: ${{ github.event.workflow_run.pull_requests[0].number }}
          message-path: |
            benchmark-comment.md
          repo-token: ${{ secrets.GITHUB_TOKEN }}
