---
name: xcop
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: xcop-${{ github.ref }}
  cancel-in-progress: true
jobs:
  xcop:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - uses: g4s8/xcop-action@v1.3
        with:
          files: |
            **/*.xsl
            **/*.xml
