# SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: xs3p
'on':
  push:
    branches:
      - master
jobs:
  xs3p:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: sudo apt-get update --yes --fix-missing && sudo apt-get install --yes xsltproc
      - run: |
          mkdir -p gh-pages/xsd
          xsltproc \
            "eo-parser/src/main/xs3p/xs3p.xsl" \
            "eo-parser/src/main/resources/XMIR.xsd" \
            > "gh-pages/XMIR.html"
      - uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          branch: gh-pages
          folder: gh-pages
          clean: false
